#!/bin/sh

VOLUME=$HOME/docker/volumes/mysql-8
mkdir -p $VOLUME

docker run \
    --rm \
    --detach \
    --name=mysql-8 \
    --env="MYSQL_ROOT_PASSWORD=root" \
    --publish 3306:3306 \
    --cpus=1 \
    --memory=1g \
    --ulimit nproc=1024 \
    --ulimit nofile=1024:1024 \
    --volume=$VOLUME:/var/lib/mysql \
    mysql:8-debian
