#!/bin/sh

VOLUME=$HOME/docker/volumes/postgres-15
mkdir -p $VOLUME

docker run \
    --rm \
    --detach \
    --name=postgres-15 \
    --env="POSTGRES_USER=postgres" \
    --env="POSTGRES_PASSWORD=postgres" \
    --cpus=1 \
    --memory=1g \
    --ulimit nproc=1024 \
    --ulimit nofile=1024:1024 \
    --publish 5432:5432 \
    --volume=$VOLUME:/var/lib/postgresql/data \
    postgres:15-alpine
