#!/bin/sh

VOLUME=$HOME/docker/volumes/mongo-6
mkdir -p $VOLUME

docker run \
--rm \
--detach \
--name=mongodb-6 \
--env="MONGO_INITDB_ROOT_USERNAME=root" \
--env="MONGO_INITDB_ROOT_PASSWORD=root" \
--publish 27017:27017 \
--volume=$VOLUME:/data/db \
mongo:6
